### ISSUE TITLE
No automatic upgrading

### ISSUE THREAD

**Issue by vilhelmprytz** [MrKaKisen/dns-manager#9]
nafsdm doesn't automatically upgrade in the latest stable version.

**Comment by vilhelmprytz** [comment]
(just added this issue for reference): will be fixed in 1.2, dev2 is in testing now.

**Comment by MrKaKisen** [comment]
Fixed in 1.2-stable! :)

**Comment by vilhelmprytz** [comment]
Fixed in 1.2-stable! :)
